### ISSUE TITLE
gimp: file-svg: plugin crashes while trying to open SVG files

### ISSUE THREAD

**Issue by thac0** [clearlinux/distribution#1018]
Saw this when I tried to open a SVG file in Gimp:

![Screenshot-sanitized](https://user-images.githubusercontent.com/3342323/61306102-d57f3380-a7a0-11e9-8f12-70a64a9a4a34.png)

That's not a good thing. I can open the same SVG in Inkscape, but that's not an acceptable work-around.

Clear Linux 30380

**Comment by lem0nez** [comment]
The similar bug is in **KDE**: applications (`.desktop` files) with SVG-icon displaying incorrectly in menu (question mark instead of icon), but in properties of the app and search results (via `F2`) icon displays correctly.

**Comment by thac0** [comment]
Still an issue as of 30580

**Comment by phmccarty** [comment]
I have identified an upstream patch that likely fixes the plugin crash. I will upgrade GIMP to 2.10.12, and assuming that works okay, apply the upstream patch and test.

**Comment by phmccarty** [comment]
The GIMP 2.10.12 release appears to work okay, so that upgrade is in queue, and I backported this patch that fixes the SVG import crash:

https://gitlab.gnome.org/GNOME/gimp/commit/38e87c2d16d0e519b35be9b2cdc9e5e28dbfab54

Expect this to be fixed in the next build, so later today or early next week.

**Comment by phmccarty** [comment]
This issue was fixed in release `30660`.

**Comment by fkkjohn** [comment]
I just got this same crash today using gimp 2.10.32 rev1. I installed the 2.10.34 update, and the problem remains. The svgs in question are all exported KiCad 6.0.10 pcb images. I'm currently updating to KiCad 7 (what a time to be alive!), but I expect it to be the same. They open fine in Libre Office Draw. They're work files, so I prefer not to share them at this time. I imagine you can easily recreate the issue by making any svg in KiCad using the export feature under the File menu.

**Comment by fkkjohn** [comment]
I'm going to copy and paste my last comment with a link to this issue as a new issue just to be sure since this one has been closed for 3.5 years.
