### ISSUE TITLE
Clearlinux docker image does not unpack with containerd

### ISSUE THREAD

**Issue by mcastelino** [clearlinux/distribution#1044]
```
sudo ctr i pull docker.io/library/clearlinux:latest
docker.io/library/clearlinux:latest:                                              resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:69a0c488fb95e0cf2bcb93ebc94c674ea49f831c54c08fd23ebb141984c50248:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:627229cee59d8049b8d74940f6ab3f2cd32e2735d85b89c3d6c193c5ba71c06b: done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:a60ee06121108a15353ad4618ef6a06358d1274f4386335445109b7d4c914041:    done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:89e73f67a1e682dbe9c4d79a1d1b2c5241ac4a13d808a33958f86a68221c2f1a:   done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 1.1 s                                                                    total:   0.0 B (0.0 B/s)
unpacking linux/amd64 sha256:69a0c488fb95e0cf2bcb93ebc94c674ea49f831c54c08fd23ebb141984c50248...
INFO[0001] apply failure, attempting cleanup             error="failed to extract layer sha256:14bf220feb5785ba23cbe5f633519da411f238fca70b2aacd88ed64d3d85ec48: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount630176201: chmod /var/lib/containerd/tmpmounts/containerd-mount630176201/sbin: no such file or directory: unknown" key="extract-958260981-GymM sha256:14bf220feb5785ba23cbe5f633519da411f238fca70b2aacd88ed64d3d85ec48"
ctr: failed to extract layer sha256:14bf220feb5785ba23cbe5f633519da411f238fca70b2aacd88ed64d3d85ec48: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount630176201: chmod /var/lib/containerd/tmpmounts/containerd-mount630176201/sbin: no such file or directory: unknown
```

Note: It works fine with docker

**Comment by mythi** [comment]
@mcastelino I'm not able to reproduce:

```
clr@k8s-master~ $ sudo ctr i pull docker.io/library/clearlinux:latest
docker.io/library/clearlinux:latest:                                              resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:03e90625a5316ee24147036bdc0269a0fae7ad258114f83a1fcfb81bdbb2701a:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:c8b92bc49a5b02aeafea40fafede841df24a0828fab2a2f761f2684f249f6395: done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:8a0388c07017e9992f7704834e5fc5a590557ffc8dc95a68e893d9d83b99dbba:    done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:ef4224047cf9bd2d33f5138607abeb813c383e6029c12853c65db55c8299f14b:   done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 12.1s                                                                    total:  58.2 M (4.8 MiB/s)
unpacking linux/amd64 sha256:03e90625a5316ee24147036bdc0269a0fae7ad258114f83a1fcfb81bdbb2701a...
done
```

I'm on baremetal at 30450 but with an older kernel 5.1.16-795.native.

**Comment by mcastelino** [comment]
@mythi I am on 
```
4.15.0-54-generic
Ubuntu 18.04.2 LTS
containerd github.com/containerd/containerd 1.2.6-0ubuntu1~18.04.2
```

I also see the issue on

```
4.20.7-042007-generic
Ubuntu 18.04.2 LTS
containerd containerd.io 1.2.6 894b81a4b802e4eb2a91d1ce216b8817763c29fb
```

**Comment by bryteise** [comment]
As usual I blame Ubuntu =P.

**Comment by mythi** [comment]
Fails here on OpenSuse too.

**Comment by luisfponce** [comment]
Same issue observed on CentOs 7:
```
Jul 24 14:05:58 c3n19-bdt containerd[194898]: time="2019-07-24T14:05:58.837097179-07:00" level=info msg="apply failure, attempting cleanup" error="failed to extract layer sha256:bf15ad2f5289ed721a33d7a454ab0648081287c84785c79178b685810497f141: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount258022960: chmod /var/lib/containerd/tmpmounts/containerd-mount258022960/var/lib/swupd/staged/2a4177b4f930e3028eb73976c4aefff149079417b3c77adbbbcafef541b72e8e: no such file or directory: unknown" key="extract-24533487-NAzw sha256:7d1beae4acdd3594dcc6a826095f9518eabbe6f0f899c0714fbf4d3ffd5196d3"
Jul 24 14:06:01 c3n19-bdt containerd[194898]: time="2019-07-24T14:06:01.876849628-07:00" level=error msg="PullImage "amr-registry-pre.caas.intel.com/clearlinux/otc-swstacks-dars-mkl:latest" failed" error="failed to pull and unpack image "amr-registry-pre.caas.intel.com/clearlinux/otc-swstacks-dars-mkl:latest": failed to unpack image on snapshotter overlayfs: failed to extract layer sha256:bf15ad2f5289ed721a33d7a454ab0648081287c84785c79178b685810497f141: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount258022960: chmod /var/lib/containerd/tmpmounts/containerd-mount258022960/var/lib/swupd/staged/2a4177b4f930e3028eb73976c4aefff149079417b3c77adbbbcafef541b72e8e: no such file or directory: unknown"
```

and

```
Aug 14 10:11:22 c3n19-bdt containerd[852]: time="2019-08-14T10:11:22.342394234-07:00" level=info msg="CreateContainer within sandbox "23d61b03b267aaac59c248630f3dead2cb57c76f73c3794f8b0f9aff9f853d26" for container &ContainerMetadata{Name:spark-worker,Attempt:0,}"
Aug 14 10:11:22 c3n19-bdt containerd[852]: time="2019-08-14T10:11:22.438013889-07:00" level=info msg="apply failure, attempting cleanup" error="failed to extract layer sha256:f3ac58c16fb4da54295cd323c5eb92fd6fb890e97cf739fb92cfba4e53d436cc: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount517918956: chmod /var/lib/containerd/tmpmounts/containerd-mount517918956/usr/bin/b2sum: no such file or directory: unknown" key="extract-386261574-GdGs sha256:f3ac58c16fb4da54295cd323c5eb92fd6fb890e97cf739fb92cfba4e53d436cc"
Aug 14 10:11:22 c3n19-bdt containerd[852]: time="2019-08-14T10:11:22.468990264-07:00" level=error msg="CreateContainer within sandbox "23d61b03b267aaac59c248630f3dead2cb57c76f73c3794f8b0f9aff9f853d26" for &ContainerMetadata{Name:spark-worker,Attempt:0,} failed" error="failed to create containerd container: error unpacking image: failed to extract layer sha256:f3ac58c16fb4da54295cd323c5eb92fd6fb890e97cf739fb92cfba4e53d436cc: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount517918956: chmod /var/lib/containerd/tmpmounts/containerd-mount517918956/usr/bin/b2sum: no such file or directory: unknown"
Aug 14 10:11:22 c3n19-bdt kubelet[100974]: E0814 10:11:22.469242  100974 remote_runtime.go:200] CreateContainer in sandbox "23d61b03b267aaac59c248630f3dead2cb57c76f73c3794f8b0f9aff9f853d26" from runtime service failed: rpc error: code = Unknown desc = failed to create containerd container: error unpacking image: failed to extract layer sha256:f3ac58c16fb4da54295cd323c5eb92fd6fb890e97cf739fb92cfba4e53d436cc: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount517918956: chmod /var/lib/containerd/tmpmounts/containerd-mount517918956/usr/bin/b2sum: no such file or directory: unknown
```

**Docker info:**
```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 58
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 029124da7af7360afa781a0234d1b083550f797c
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-957.21.3.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 72
 Total Memory: 377.6GiB
 Name: c3n19-bdt
 ID: 5B53:5MNX:HNA3:R2CG:WPEZ:NWTU:F3WL:JASN:AFUM:QOLE:QWSM:LQCM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://proxy-us.intel.com:911
 No Proxy: localhost,intel.com
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**containerd version:**
```
containerd github.com/containerd/containerd v1.2.6 894b81a4b802e4eb2a91d1ce216b8817763c29fb
```

**Comment by ganeshmaharaj** [comment]
@mcastelino Issue fixed with https://github.com/clearlinux/distribution/issues/1107

**Comment by rojkov** [comment]
@bryteise I tried the fix proposed in #1107 and restarted conteinerd, but it didn't help. I still get errors when pulling Clearlinux images to containerd:
```
$ sudo ctr i pull docker.io/library/clearlinux:latest
docker.io/library/clearlinux:latest:                                              resolved       |++++++++++++++++++++++++++++++++++++++| 
index-sha256:7c52533bd88ff54e2ff59ef81f13826de526a9c1191133de84c28eef50dd6699:    done           |++++++++++++++++++++++++++++++++++++++| 
manifest-sha256:6c5d832491844f8bbe179e855351bc07c5ff9ab7c0670d3d18c1f21be6305cf4: done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:3b76b7f129b3b411ba4401b4972644e078ca8be02adc74e550168b455812979b:    done           |++++++++++++++++++++++++++++++++++++++| 
config-sha256:ac647b2ff3195b68671020aac4c8afe0d2d6f443ed84e6784b1799d68d85e172:   done           |++++++++++++++++++++++++++++++++++++++| 
elapsed: 23.1s                                                                    total:  58.0 M (2.5 MiB/s)                                       
unpacking linux/amd64 sha256:7c52533bd88ff54e2ff59ef81f13826de526a9c1191133de84c28eef50dd6699...
INFO[0023] apply failure, attempting cleanup             error="failed to extract layer sha256:33a4f7502f50042c2651d7d50f3188a936b51cb99b87864c1b86fdaf7665fb56: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount882729530: chmod /var/lib/containerd/tmpmounts/containerd-mount882729530/usr/bin/b2sum: no such file or directory: unknown" key="extract-249714720-WMX4 sha256:33a4f7502f50042c2651d7d50f3188a936b51cb99b87864c1b86fdaf7665fb56"
ctr: failed to extract layer sha256:33a4f7502f50042c2651d7d50f3188a936b51cb99b87864c1b86fdaf7665fb56: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount882729530: chmod /var/lib/containerd/tmpmounts/containerd-mount882729530/usr/bin/b2sum: no such file or directory: unknown
```

I'm on Fedora 30
```
$ sudo ctr version
Client:
  Version:  1.2.10
  Revision: b34a5c8af56e510852c35414db4c1f4fa6172339

Server:
  Version:  1.2.10
  Revision: b34a5c8af56e510852c35414db4c1f4fa6172339

$ uname -a
Linux snoopy 5.3.16-200.fc30.x86_64 #1 SMP Fri Dec 13 17:48:38 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rojkov** [comment]
The same error happens with all Clearlinux images built with Docker. If an image is built with Buildah it unpacks successfully in containerd.

**Comment by bryteise** [comment]
@rojkov What is the overlayfs config for the kernel in that fedora? Also what is in the service file for containerd?

**Comment by rojkov** [comment]
@bryteise The relevant kernel config is
```
CONFIG_OVERLAY_FS=m
# CONFIG_OVERLAY_FS_REDIRECT_DIR is not set
CONFIG_OVERLAY_FS_REDIRECT_ALWAYS_FOLLOW=y
# CONFIG_OVERLAY_FS_INDEX is not set
# CONFIG_OVERLAY_FS_XINO_AUTO is not set
# CONFIG_OVERLAY_FS_METACOPY is not set
```

```
$ cat /usr/lib/systemd/system/containerd.service
[Unit]
Description=containerd container runtime
Documentation=https://containerd.io
After=network.target

[Service]
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/bin/containerd
KillMode=process
Delegate=yes
LimitNOFILE=1048576
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity

[Install]
WantedBy=multi-user.target

```

**Comment by bryteise** [comment]
So looking at [CONFIG_OVERLAY_FS_REDIRECT_ALWAYS_FOLLOW](https://cateee.net/lkddb/web-lkddb/OVERLAY_FS_REDIRECT_ALWAYS_FOLLOW.html) I am wondering if that's causing your problem as maybe the docker image build has this enabled. Any chance you'd try out a custom kernel with that option disabled and see if you still have the issue with docker images?
