### ISSUE TITLE
Let's include ripgrep

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/distribution#197]
**List the package(s) you would like to see updated**
https://github.com/BurntSushi/ripgrep

**Does this update provide any significant new features that may be needed**
This is some smart and useful version of grep and it could make life at the command line easier. It is grep + awk combined, with some extra powers and it's faster than the usual grep | awk

**Comment by AntonioMeireles** [comment]
include and make available as a pundle too :-)

**Comment by lennyxc** [comment]
Any updates here on on handling cargo? Looking for ripgrep as well.

**Comment by mpurzynski** [comment]
Ping from me as well. We already have the Rust support and cargo seems like the next logical element here.

**Comment by bryteise** [comment]
Still working on Java and go support in autospec. Likely ruby and rust support follows.

**Comment by gorakhargosh** [comment]
+1

**Comment by romulasry** [comment]
Update?

**Comment by insilications** [comment]
I'm compiling it with the nightly version of rust in my Intel CPU. It is very fast. It will be amazing once this gets its own bundle in CL.

**Comment by WSLUser** [comment]
A quick easy way to get this installed would be to use homebrew. Simply adapt this for Clear Linux: https://github.com/WhitewaterFoundry/pengwin-setup/blob/master/pengwin-setup.d/brew.sh

**Comment by paulcarroty** [comment]
Any progress?

**Comment by bryteise** [comment]
I don't expect we'll be picking this up soon as ripgrep's source archive doesn't vendor its dependencies making building offline painful.

**Comment by paulcarroty** [comment]
Done after 5 years 😀

**Comment by carlosvigil** [comment]
> Done after 5 years grinning

How do we install it? Sometimes I get this:
```
swupd search ripgrep
Component ripgrep has version 13.0.0
```
and others:
```
swupd search ripgrep
Search failed, no reasonable results found
```

I tried searching in a browser but I still can't find it.
