### ISSUE TITLE
Daylight saving bug.

### ISSUE THREAD

**Issue by jumpinggoofballs** [clearlinux/distribution#2168]
With:

1) Automatic Date & Time: ON
2) Automatic Time Zone: OFF

my time is currenly stuck on Summer daylight saving time, even though it should have changed last night.

I'm in the London timezone, which should be BST in the Summer and GMT during the Winter. It currently remains on BST.

Thought: It is also possible that this is due to assumptions made about when the switchover happens. In the UK this is usually a week or two before it happens in the US.

**Comment by gregor160300** [comment]
Same here for Amsterdam time, with or without automatic time zone

**Comment by alexsantos** [comment]
Same here for Portugal for only for Gnome. 

![image](https://user-images.githubusercontent.com/932219/97173475-8cca6e80-1788-11eb-865f-7b13a9bcebea.png)

![image](https://user-images.githubusercontent.com/932219/97173531-a2d82f00-1788-11eb-8039-25239fbe0c9f.png)

**Comment by fenrus75** [comment]
so this is all .. odd

the system is set to UTC, and then an adjustment is made for the timezone
that the app is using to present the time.
I wonder how this would go all ok EXCEPT for DST. I could see easily how
"UTC" could be (lacking all info for example)
but all BUT the daylight savings is much more weird

**Comment by thiagomacieira** [comment]
Ok, so a GNOME bug. The problem is not the timezone files.

Can anyone say if logging out and back in solves the problem? Maybe some GNOME library code loaded the offset and timezone name before the transition and forgot to update.

**Comment by jumpinggoofballs** [comment]
> Can anyone say if logging out and back in solves the problem? Maybe some GNOME library code loaded the offset and timezone name before the transition and forgot to update.

No, that does not solve the problem. I have logged out and back in several times since yesterday.

**Comment by chrysophylax** [comment]
I am running the system on UTC but use the GNOME world clocks feature to keep track of some clocks and I see the same error wrt to DST.

tzdata looks fine running a zdump -v Europe/Stockholm
but World Clocks insists on setting Stockholm to +2
![image](https://user-images.githubusercontent.com/10576351/97446425-4ad72f00-1926-11eb-8b0f-599cbc19c2b8.png)

**Comment by romulasry** [comment]
Is this a upstream bug?

**Comment by jjw** [comment]
> Is this a upstream bug?

Almost certainly.  There have been historical issues with Gnome clock getting "stuck" with an inappropriate timezone offset. Logging out and/or rebooting does not help. It is reported that removing the applet and re-installing it works (or at least leaves it stuck on the currently correct timezone) but I have not been able to verify this.  Other remedies suggested include installing network-time-sensitive (no effect) and enabling location services and automatic timezone (no effect). 

The fact that the system time is correct but the clock is wrong suggests to me that it is the clock that is at fault.

Actually, I think it's Gnome's handling of time throughout the system. The timestamp in the filename of the screenshot I took shows the wrong time too...

![Screenshot_2020-10-30_09-24-38](https://user-images.githubusercontent.com/8708/97678470-c0a8db00-1a8b-11eb-93e8-51d04c07b0e5.png)

Jerry

**Comment by chrysophylax** [comment]
Will Intel ClearLinux team report the bug upstream?

**Comment by romulasry** [comment]
https://gitlab.gnome.org/GNOME here is their gitlab, don't know which project though, anyone know?

**Comment by alexsantos** [comment]
Gnome 3.36 is showing it correctly on a fresh install of CL. After updating to 3.38 it shows this wrong behavior.

**Comment by takov** [comment]
As alexsantos said it works with older version of CL
OS: 33590
GNOME: 3.36.2

I am afraid to upgrade now :)

**Comment by romulasry** [comment]
https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/1179

**Comment by romulasry** [comment]
Go ahead and post here what library and version needs updated to fix this (when available).

**Comment by romulasry** [comment]
A fix was made to 2.66 branch waiting for them to push the fix there. https://gitlab.gnome.org/GNOME/glib/-/tags

**Comment by xaverh** [comment]
The same issue currently appears in Go programs (Clear Linux version 33940):

A minimal example is:

tztest.go
```go
package main

import (
        "fmt"
        "time"
)

func main() {
        t := time.Now()
        zone, _ := t.Zone()
        fmt.Println(zone)
}
```
built with
```sh
go build tztest.go
```

Running it with
```sh
TZ=Europe/Berlin ./tztest
```
returns `CEST`, but it should return `CET` since Germany is not on daylight saving time right now.

Same problem for
```sh
TZ=America/New_York ./tztest
```
which should not be `EDT` right now.

**Comment by mdhorn** [comment]
> The same issue currently appears in Go programs (Clear Linux version 33940):
> 

Interesting. I'm not able to reproduce these results on older or recent versions of Clear Linux.

What is the result of: `zdump -v Europe/Berlin | grep 2020`

```
Europe/Berlin  Sun Mar 29 00:59:59 2020 UT = Sun Mar 29 01:59:59 2020 CET isdst=0 gmtoff=3600
Europe/Berlin  Sun Mar 29 01:00:00 2020 UT = Sun Mar 29 03:00:00 2020 CEST isdst=1 gmtoff=7200
Europe/Berlin  Sun Oct 25 00:59:59 2020 UT = Sun Oct 25 02:59:59 2020 CEST isdst=1 gmtoff=7200
Europe/Berlin  Sun Oct 25 01:00:00 2020 UT = Sun Oct 25 02:00:00 2020 CET isdst=0 gmtoff=3600
```

Do you have the tzdata bundle installed? `swupd bundle-list | grep tzdata`

Are there tz files in /usr/share/zoneinfo?

Does the date command return the right value? `TZ=Europe/Berlin date`

Does `sudo swupd diagnose` show any issues?

Do you have the file '/etc/adjtime'?

Does this system run a network time sync service NTP or chronyd?

**Comment by jjw** [comment]
> The same issue currently appears in Go programs (Clear Linux version 33940):

You may not use GNOME but does your Go compiler link aginst glib (the upstream bug is in glib)?

**Comment by xaverh** [comment]
I'm using the go compiler of the official Clear Linux go-basic bundle.

**Comment by jjw** [comment]
Thanks for taking the effort to help, but I'm not sure it's a tzdata issue; see the above comments about upstream bugs.

> What is the result of: `zdump -v Europe/Berlin | grep 2020`
Identical to yours.

> Do you have the tzdata bundle installed? `swupd bundle-list | grep tzdata`
 - tzdata

> > Are there tz files in /usr/share/zoneinfo?
$ ls /usr/share/zoneinfo/ | wc -l
67

> Does the date command return the right value? `TZ=Europe/Berlin date`
I assume so: Mon 16 Nov 21:02:37 CET 2020
I'm in the UK and date returns the correct value, as does timedatectl; it's just the clock and other programs compiled against glib (e.g snapshot) that fail to determine the correct time.

> Does `sudo swupd diagnose` show any issues?
Ironically, yes;  -> Hash mismatch for file: /usr/lib64/mysql/plugin/auth_pam_tool_dir

But I'll investigate that separately!!

> Do you have the file '/etc/adjtime'?
No

> Does this system run a network time sync service NTP or chronyd?
No, the default for CL: systemd-timesync

Thanks for the suggestions, but I don't think this is it.  Cheers, Jerry

**Comment by thiagomacieira** [comment]
stracing the run of that Go application shows it opened no file in /usr/share/zoneinfo.

That means this is a defect in the Go compiler or standard library: it hardcoded the timezone information instead of reading off of the system tzdata.

**Comment by mdhorn** [comment]
> stracing the run of that Go application shows it opened /usr/share/zoneinfo//Europe/Berlin then printed "CEST"
> 
> My guess is that the Go standard library has the same bug.

If that were true, then this would be reproducible, no?

**Comment by thiagomacieira** [comment]
> If that were true, then this would be reproducible, no?

Right. It is reproducible.

**Comment by mdhorn** [comment]
> > If that were true, then this would be reproducible, no?
> 
> Right. It is reproducible.

No, it is not on my system. So....

**Comment by thiagomacieira** [comment]
It was on mine, with the exact test case as supplied. It printed "CEST" instead of "CET".

**Comment by phmccarty** [comment]
As of tzdata 2020b, the default format of zoneinfo files is now `slim` instead of `fat`, and upstream golang did not support the `slim` format until a few days ago. See https://github.com/golang/go/issues/42155.

**Comment by xaverh** [comment]
I can confirm the Go problem has been fixed with the latest update. :+1: Thanks!

**Comment by random-user-00** [comment]
I use CET time and I was little bit humiliated during presentations by this bug. So I tried few things and found a workaround. I set the TZ env variable in ~/.profile, did logout/login and now Gnome top bar is showing correct time. 
`export TZ='CET-1CEST,M3.5.0/2,M10.5.0/3'`

Caution: I have no clue how this TZ variable is calculated for each timezone. I tried to understand it but finally gave up. Just googled for 'TZ variable for CET' and used that.

**Comment by jjw** [comment]
Oooh, interesting.  I wasn't aware of this use of TZ.  Looking at it, it shows <Zone tag><Offset from UTC><Summer Zone tag>,<Date of change from Normal to Summer>,<Date of change back>

From https://sites.google.com/a/usapiens.com/opnode/time-zones my UK version is 'GMT+0BST-1,M3.5.0/01:00:00,M10.5.0/02:00:00'.  I would guess that "M3" refers to Month 3 (March) and that '5' means the 5th (last) and '0' Sunday at 01:00 which matches the UK rules.  I presume that CET moves at 2am to 3am ?

You should note that in the unlikely event that your timezone rules change, then this hardcoded value will be wrong.  But as a workaround for this stupid Gnome bug it's fantastic - well done!  (I cannot believe they have not rolled out a fix yet - I thought we cracked all this crap back in the 80s)

**Comment by jumpinggoofballs** [comment]
Okay, so it is getting on to two months since I opened this bug. I think this might be the time to share some _thoughts_.

Obviously this is not a _huge_ deal for most desktop users of Clear OS. But it is a very _obvious_ deal. 

I understand that the Clear OS team is not all that interested in maintaining the desktop side of the distro, and the focus is squarely on the server. I know what I am signing up for when I run the distro on my local workstation.

I also understand the inclination of the OS team to keep everything exactly as it comes down from upstream. In fact, I agree with that position in general. 

But is it really that big of an ask to expect that this kind of bug would have a provisional patch applied on top of the upstream, within, say two weeks of it appearing. I mean, do none of the maintainers of the distro use it for their workstations? 

If that is the case, I believe that this one should be an obvious thing to bother / petition the "powers that be" (/Intel) about: the people who maintain the Clear OS stack should be running Clear OS on the work computers. Dogfooding. 

I hate to be that guy, but is this really too much to ask?

**Comment by AlessandroFasse** [comment]
I have to say the same. This distro is so good and I never want to use another one. But these obvious but annoying bugs should be fixed. Please!

**Comment by jjw** [comment]
I have to say that it was partly fixed for me by some recent update but I did not notice when.  The clock now displays the correct time, but the graphical time-zone chooser is still screwed.

I'm on 34100...

**Comment by jumpinggoofballs** [comment]
> I'm on 34100...

34130 here and still no luck. So for now I "live" in Reykjavík.

**Comment by romulasry** [comment]
Fix is in the latest glib:
https://gitlab.gnome.org/GNOME/glib/-/releases#2.67.2

**Comment by swartzlib7** [comment]
> I use CET time and I was little bit embarrassed during presentations because this bug. So I tried few things and found a workaround. I set the TZ env variable in ~/.profile, did reboot and now Gnome top bar is showing correct time. It still shows wrong time on login screen though.
> `export TZ='CET-1CEST,M3.5.0/2,M10.5.0/3'`
> 
> Caution: I have no clue how this TZ variable is calculated for each timezone. I tried to understand it but finally gave up. Just googled for 'TZ variable for CET' and used that.


Thank you this helped me fix the issue on Clear Linux with GNOME 3.38.3
I'm in Florida so for EST I had to add this to ~/.profile `export TZ='CET+5CEST,M3.5.0/2,M10.5.0/3'`

**Comment by phmccarty** [comment]
Hi all, I just integrated an update to glib to fix the timezone handling bug from the original report. Expect to see glib 2.66.6 (or a newer 2.66.x release) land in Clear Linux 34260 (or newer). ETA early next week.

Here is some more detail about additional glib packaging changes I made:

- The glib build is now configured with `-Dglib_assert=false`.
  - Because the default build option is `-Dglib_assert=true`, I suspect this configuration was the root cause of gnome-shell crashing with failed assertions in JS code, the underlying reason for the GNOME desktop failing to launch when we updated to GNOME 3.38 in September 2020. At the time, we had downgraded glib to 2.64.x after the observed breakage, thereby avoiding the assertions.
- A shared-mime-info database is now populated in the package build root to improve glib unit test coverage.
  -  The shared-mime-info integration in Clear Linux OS is customized to accommodate the concept of statelessness in the distro. One side effect of the integration is that the shared-mime-info database is not populated by default in a package build root. Some glib unit tests expect the shared-mime-info to be available, so my solution here was to populate the database under `~/.local/share/mime`, one of the several valid locations for the mime database.

**Comment by romulasry** [comment]
@phmccarty Go ahead and close this when that lands and fixes this bug. Thanks in advance.

**Comment by random-user-00** [comment]
Thanks @phmccarty
I can confirm that this has been fixed in release 34260.

**Comment by phmccarty** [comment]
Great, thank you for confirming :-) The fix did land in release 34260, so I will close.
