### ISSUE TITLE
QXL support broken: undefined symbol: fbImageGlyphBlt

### ISSUE THREAD

**Issue by ahkok** [clearlinux/distribution#222]
**Describe the bug**
Qemu QXL support is broken when running Clear on Clear using qemu with the `-vga qxl -display gtk` options

![qxl](https://user-images.githubusercontent.com/24399627/46553613-cfb00580-c892-11e8-97fd-6b66bf34cb02.png)

**Comment by ahkok** [comment]
`libfb.so` has `fbImageGlyphBlt`, but `libglamoregl.so` hasn't? I'm not really sure what's the issue here...

**Comment by bryteise** [comment]
@ahkok This is due to the use of the Clear Linux's default CFLAGS when building xf86-video-qxl instead of the minimal set. @fenrus75 fixed the package so this should be resolved in the next release.

**Comment by ahkok** [comment]
Confirmed fixed. Even though `gdm` is still broken somehow, I was able to `startx` with `qxl` support and get a full graphical desktop under qemu!
