### ISSUE TITLE
Gnome Online Accounts couldn't add account

### ISSUE THREAD

**Issue by lifers** [clearlinux/distribution#2284]
**Description**
In Gnome Settings, I tried to add a Google account but it stuck at the pop-up window. Waiting for fifteen minutes and still stuck.

**Clear Linux version**
`34270`, fresh install

**How to Reproduce**
Make sure the computer is connected to the internet. Click the Google option in the Online Accounts section in Gnome Settings. The pop-up window will show up, but it only shows a tiny blue bar (looks like a progress bar) at the top left and nothing else.

**Expected Outcome**
The pop-up window should display Google Account sign-in page.

**Additional Information**
```
$ gnome-control-center --verbose
17:37:32.0347                      GLib:    DEBUG: setenv()/putenv() are not thread-safe and should not be used after threads are created
17:37:32.0354      diagnostics-cc-panel:    DEBUG: ABRT vanished
(process:12024): GLib-GIO-DEBUG: 17:37:35.550: Failed to initialize portal (GNetworkMonitorPortal) for gio-network-monitor: Not using portals
(process:12024): GLib-GIO-DEBUG: 17:37:35.551: _g_io_module_get_default: Found default implementation networkmanager (GNetworkMonitorNM) for ?gio-network-monitor?
(process:12024): GLib-GIO-DEBUG: 17:37:35.553: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ?gio-vfs?
(WebKitWebProcess:2): GVFS-RemoteVolumeMonitor-DEBUG: 17:37:35.557: Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

(WebKitWebProcess:2): GVFS-DEBUG: 17:37:35.559: org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

(WebKitWebProcess:2): GLib-GIO-DEBUG: 17:37:35.559: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’

(WebKitWebProcess:2): GLib-GIO-ERROR **: 17:37:35.590: No GSettings schemas are installed on the system
** (process:12018): DEBUG: 17:37:35.692: Error reading from socket: Error receiving message: Connection reset by peer
(process:12170): GLib-GIO-DEBUG: 17:40:19.765: Failed to initialize portal (GNetworkMonitorPortal) for gio-network-monitor: Not using portals
(process:12170): GLib-GIO-DEBUG: 17:40:19.766: _g_io_module_get_default: Found default implementation networkmanager (GNetworkMonitorNM) for ?gio-network-monitor?
(process:12170): GLib-GIO-DEBUG: 17:40:19.768: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ?gio-vfs?
(WebKitWebProcess:2): GVFS-RemoteVolumeMonitor-DEBUG: 17:40:19.774: Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

(WebKitWebProcess:2): GVFS-DEBUG: 17:40:19.776: org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

(WebKitWebProcess:2): GLib-GIO-DEBUG: 17:40:19.777: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’

(WebKitWebProcess:2): GLib-GIO-ERROR **: 17:40:19.808: No GSettings schemas are installed on the system
** (process:12018): DEBUG: 17:40:19.906: Error reading from socket: Error receiving message: Connection reset by peer
(gnome-control-center:11998): dconf-DEBUG: 17:47:51.135: unwatch_fast: "/org/gnome/control-center/" (active: 1, establishing: 0)
(gnome-control-center:11998): dconf-DEBUG: 17:47:51.135: sync
17:47:51.0136         cc-object-storage:    DEBUG: Destroying cached objects
```
In this attempt I clicked the Google option then the Microsoft option, both showing blank pop-up window.

**Comment by lifers** [comment]
I found a workaround,
```
$ sudo glib-compile-schemas /usr/share/glib-2.0/schemas
```
I ran this command and I was able to login successfully, even after reboot.
Source: https://lists.clearlinux.org/hyperkitty/list/dev@lists.clearlinux.org/thread/EO652QBF457TCAGRDJX2FGHIS5332EBU/

**Comment by lebensterben** [comment]
This used to be an issue but have been fixed in 2019 or 2020 I think....

**Comment by mdhorn** [comment]
@mdhorn I'll attempt to recreate this when I get some cycles, but seems there is at least a workaround.

**Comment by plegrand1** [comment]
Same problem here, but the command 
"glib-compile-schemas /usr/share/glib-2.0/schemas" 
doesn't solve the problem

**Comment by mdhorn** [comment]
I'm able to reproduce this on a fresh install of the latest 34370, but the noted workaround did enable account logins.
I'll see if there is a pre-compiled package that needs updating after the update to 3.38.

**Comment by mdhorn** [comment]
Are compiling the schemas and placing then in /var/cache/glib-2.0/schemas/gschemas.compiled
but it appears they are not being picked up under that path.
Need to dig into adding that path either through a patch or setting the appropriate environment variable before the settings daemon is started.

**Comment by phmccarty** [comment]
@mdhorn This is the patch that is intended to make glib recognize that location:

https://github.com/clearlinux-pkgs/glib/blob/5dbf14ac6f/0001-gio-Support-a-stateless-configuration-for-compiled-G.patch

**Comment by mdhorn** [comment]
I can verify that the patch is working, I can see the code execute adding that path.
But something else is not seeing the directory be added.

**Comment by mdhorn** [comment]
Rolled back to 33710, with glib 2.64.5 and this was working. 
Stepping through the upgrades to find the breaking point to help isolate the change set.

**Comment by DroneZzZko** [comment]
Downloaded **34930** and the issue still persists. Any update on this?

**Comment by rkunschke** [comment]
Still the same problem for me and its realy annoying.
Is there any good pratice to apply the patch to test it?
Is there a reason thr patch is not merged already?

**Comment by VooqadAfterburner** [comment]
The above works for me to

**Comment by iyarsius** [comment]
hi, same error here, i can see the popup and type my email but when i press enter to access password page, popup is stuck on loading and freeze.

i tried solutions from this topic but nothing happen

**Comment by airtonix** [comment]
@iyarsius 

try 
```
env WEBKIT_DISABLE_COMPOSITING_MODE=1 gnome-control-center online-accounts
```

I've turned this into a desktop file named `Online Accounts (Fixed)` so i dont have to remember.

![image](https://github.com/clearlinux/distribution/assets/61225/124f6f5e-2f48-47ee-8fda-8a49c8ec9dfd)

```
[Desktop Entry]
Version=1.1
Type=Application
Name=Online Accounts (Fixed)
Icon=avatar-default-symbolic.symbolic
Exec=env WEBKIT_DISABLE_COMPOSITING_MODE=1 gnome-control-center online-accounts
Actions=
Categories=Utility;
```

**Comment by sincorchetes** [comment]
I had a fresh install. It's worked without performing any additional steps.

**Comment by MrPerezident** [comment]
> @iyarsius
> 
> try
> 
> ```
> env WEBKIT_DISABLE_COMPOSITING_MODE=1 gnome-control-center online-accounts
> ```
> 
> I've turned this into a desktop file named `Online Accounts (Fixed)` so i dont have to remember.
> 
> ![image](https://private-user-images.githubusercontent.com/61225/304615188-124f6f5e-2f48-47ee-8fda-8a49c8ec9dfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NzEwNjEsIm5iZiI6MTcxNjc3MDc2MSwicGF0aCI6Ii82MTIyNS8zMDQ2MTUxODgtMTI0ZjZmNWUtMmY0OC00N2VlLThmZGEtOGE0OWM4ZWM5ZGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAwNDYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzNTFkMzRmYjAzMTlkZDFlMTQyMGM4YjlmYzU2YmQxZWNhMzk5NDQ1Y2E3ZDFiNTM4ODRhMGQyZjgxY2IwNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h-uRwz4v4V23Nxo2DbQMGf1qxlQpovOzVPZOQhuO94g)
> 
> ```
> [Desktop Entry]
> Version=1.1
> Type=Application
> Name=Online Accounts (Fixed)
> Icon=avatar-default-symbolic.symbolic
> Exec=env WEBKIT_DISABLE_COMPOSITING_MODE=1 gnome-control-center online-accounts
> Actions=
> Categories=Utility;
> ```

This one worked for me. Linux Mint 21.3 
![Screenshot from 2024-05-26 19-47-28](https://github.com/clearlinux/distribution/assets/15951017/5c92a238-19eb-4065-b289-b21f6e750de5)

**Comment by diztorded** [comment]
This worked also on LMDE 6 Faye:

Exec=env WEBKIT_DISABLE_COMPOSITING_MODE=1 cinnamon-settings online-accounts

**Comment by bwarden** [comment]
This issue is specific to Clear Linux and is unrelated to the WebKit issue that affected other distributions.

Underlying problem is that glib wouldn't resolve the custom schema that's used to receive the OAuth2 callback from the browser because we store the mimeinfo cache for /usr/share/applications under /var/cache/applications. Fix is in the works and should bump here when it's published. You'll need to reboot after updating for GNOME to reload the affected libraries.
