### ISSUE TITLE
OS Version 37710 | Kernel 6.0.10 fails to load firmware for RTL8192EE PCIe Wireless Network Adapter

### ISSUE THREAD

**Issue by mmorini** [clearlinux/distribution#2779]
Apparently, firmware rtlwifi/rtl8192eefw.bin is no longer available. Context follows.

Log (per journalctl)

Dec 02 18:21:49 robin2 kernel: calling  rtl92ee_driver_init+0x0/0x1000 [rtl8192ee] @ 459
Dec 02 18:21:49 robin2 kernel: rtl8192ee 0000:05:00.0: enabling device (0000 -> 0003)
Dec 02 18:21:49 robin2 kernel: rtl8192ee: Using firmware rtlwifi/rtl8192eefw.bin
Dec 02 18:21:49 robin2 kernel: rtl8192ee 0000:05:00.0: Direct firmware load for rtlwifi/rtl8192eefw.bin failed with error -2
Dec 02 18:21:49 robin2 kernel: rtlwifi: Selected firmware is not available

Device (per lspci -v)

05:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8192EE PCIe Wireless Network Adapter
        Subsystem: Realtek Semiconductor Co., Ltd. RTL8192EE PCIe Wireless Network Adapter
        Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0, Cache Line Size: 64 bytes
        Interrupt: pin A routed to IRQ 75
        IOMMU group: 17
        Region 0: I/O ports at d000 [size=256]
        Region 2: Memory at f6500000 (64-bit, non-prefetchable) [size=16K]
        Capabilities: <access denied>
        Kernel driver in use: rtl8192ee
        Kernel modules: rtl8192ee

**Comment by mmorini** [comment]
Placing the binary blob where expected fixes things.

ref: https://kernel.googlesource.com/pub/scm/linux/kernel/git/firmware/linux-firmware/+/4164c23d2e3b4863ca42d72f40dc7cc5d9fb8c6c

**Comment by Cueropedo** [comment]
I'm having the same issue, my Realtek PCI card is not working and I lost Wi-Fi connectivity...

**Comment by bwarden** [comment]
Looks like some of the WiFi firmware was inadvertently dropped a while ago. I've added it back, so it should be available in a release soon, in the linux-firmware-wifi bundle.

**Comment by Cueropedo** [comment]
> Looks like some of the WiFi firmware was inadvertently dropped a while ago. I've added it back, so it should be available in a release soon, in the linux-firmware-wifi bundle.

Will I have to install that "linux-firmware-wifi", or it will just install the Wi-Fi firmware itself in the next update?

**Comment by bwarden** [comment]
You may already have the bundle installed, but if not, you can install it manually (`sudo swupd bundle-add linux-firmware-wifi`), and either way the firmware file will be added automatically when your system updates to the new release.

This will show you the current status on your system. I don't know what version will contain my change yet.
```
$ sudo swupd bundle-info linux-firmware-wifi
______________________________________
 Info for bundle: linux-firmware-wifi
______________________________________

Status: Explicitly installed

Bundle linux-firmware-wifi is up to date:
 - Installed bundle last updated in version: 37630
 - Latest available version: 37630

Bundle size:
 - Size of bundle: 186.53 MB
 - Size bundle takes on disk (includes dependencies): 278.87 MB
```

**Comment by bwarden** [comment]
Should be fixed in release 37730.

**Comment by mmorini** [comment]
Confirm missing firmwares are shipped with 37730, but loading still fails. It appears the symlink doesn't cut it. The plot thickens.

Dec 11 20:06:06 robin2 kernel: rtl8192ee 0000:05:00.0: enabling device (0000 -> 0003)
Dec 11 20:06:06 robin2 kernel: rtl8192ee: Using firmware rtlwifi/rtl8192eefw.bin
[...]
Dec 11 20:06:06 robin2 kernel: rtl8192ee 0000:05:00.0: Direct firmware load for rtlwifi/rtl8192eefw.bin failed with error -2
Dec 11 20:06:06 robin2 kernel: rtlwifi: Selected firmware is not available
[...]
Dec 11 20:06:18 robin2 kernel: rtl8192ee: Polling FW ready fail!! REG_MCUFWDL:0x00070406. count = 3001

**Comment by bwarden** [comment]
Ahhh, we do an extra compression step that didn't comprehend the symlink, so it compressed `rtl8192eu_nic.bin` to `rtl8192eu_nic.bin.zst` and left the symlink dangling:
```
$ ls -l /usr/lib/firmware/rtlwifi/rtl8192eefw.bin 
lrwxrwxrwx 1 root root 17 Feb  1  2019 /usr/lib/firmware/rtlwifi/rtl8192eefw.bin -> rtl8192eu_nic.bin
$ ls -l /usr/lib/firmware/rtlwifi/rtl8192eu_nic.bin*
-rw-r--r-- 1 root root 20043 Feb  1  2019 /usr/lib/firmware/rtlwifi/rtl8192eu_nic.bin.zst
$ 
```
I'll work out a fix.

**Comment by mmorini** [comment]
Voilà! :partying_face:

**Comment by Cueropedo** [comment]
> In the short term, until my fix rolls out, you can do: `ln -s /usr/lib/firmware/rtlwifi/rtl8192eefw.bin.zst rtl8192eu_nic.bin.zst`

I will try it with `ln -s /usr/lib/firmware/rtlwifi/rtl8723befw.bin.zst` in my case.

**Comment by mmorini** [comment]
Fixed in 37740, thanks!

**Comment by Cueropedo** [comment]
Um.... I tried the new version, but Wi-Fi/Bluetooth is still not working for me, should I open a new issue referring to this?

**Comment by Cueropedo** [comment]
@mmorini Is Wi-Fi still working for you? In my case it broke yet again in 37870 using Kernel 6.1.1-1229.native...
