### ISSUE TITLE
[CL 41150] GNOME Night Light is broken

### ISSUE THREAD

**Issue by Cueropedo** [clearlinux/distribution#3059]
Right now, GNOME's night light is broken, when you enable the option in settings, nothing happens. As of writting, I'm using the latest CL OS version (41150).

**Comment by ilmarn** [comment]
sudo swupd bundle-add xdg-desktop-portal-gnome xdg-desktop-portal

should fix this

**Comment by fenrus75** [comment]
if those are what's missing I'll make sure to get those included by default
in the desktop install/bundle

**Comment by Cueropedo** [comment]
> sudo swupd bundle-add xdg-desktop-portal-gnome xdg-desktop-portal
> 
> should fix this

I installed those, rebooted, but it doesn't seem to fix it. I don't recall having to install any additional bundles in the past for Night Light to work, I did try at one point with a clean Clear Linux install and it doesn't seem to be working there either.

**Comment by ilmarn** [comment]
also had this problem. will try to explain what i did

installed xdg-desktop-portal, rebooted, didnt fixed it
tried gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'. didnt worked also, removed xdg-desktop-portal
after a couple of days reinstalled xdg-desktop-portal, rebooted, set dark mode and rebooted, some magic happened it and now its working

**Comment by Cueropedo** [comment]
I see, still I believe this is something really basic and should be working out-of-the-box without the need of workarounds. But still thanks for your input here! Let's hope the devs fix this.
