### ISSUE TITLE
Enable disk quota

### ISSUE THREAD

**Issue by melanopsis** [clearlinux/distribution#3265]
Hi, I'm trying to enable project quota (pquota) for an XFS filesystem but according to dmesg,  `XFS (loop0): quota support not available in this kernel.` Do you think this can be enabled?

**Comment by fenrus75** [comment]
done -- will be in the next release

thanks for the report

**Comment by melanopsis** [comment]
Awesome. Thank you for the prompt action!

**Comment by melanopsis** [comment]
Hi @fenrus75, I just tried the 43030 release but I still see the same message in dmesg.

``` [   12.004136] calling  init_xfs_fs+0x0/0x3e0 [xfs] @ 363
    [   12.004337] SGI XFS with ACLs, security attributes, realtime, no debug enabled
    [   12.004713] initcall init_xfs_fs+0x0/0x3e0 [xfs] returned 0 after 426 usecs
    [   12.006280] XFS (nvme1n1): quota support not available in this kernel.```

**Comment by melanopsis** [comment]
I forgot to mention, this is on the linux-aws kernel.

**Comment by fenrus75** [comment]
ah ha will poke that one tomorr6

**Comment by melanopsis** [comment]
Thanks! It works as expected.
