### ISSUE TITLE
RFE: package, and ship by default, xf86-video-vmware

### ISSUE THREAD

**Issue by AntonioMeireles** [clearlinux/distribution#546]
Hi all!, 

When running ClearLinux over VMware (fusion, etc) in non-headless mode the display performance is, at best, sup-optimal. 

This is due to the fact that the the `x11-server` bundle is not shipping [`xf86-video-vmware`](https://cgit.freedesktop.org/xorg/driver/xf86-video-vmware). Digging deeper AFAICT `xf86-video-vmware` is not even being packaged. 

So i'd suggest to package it and ship it by default in the  `x11-server` bundle. Overhead is minimal and Xorg's auto-detection will do the rest...

Steps to reproduce: 
- assuming a **Vagrant** host - a `Vagrantfile` with the following contents: 
```ruby
required_plugins = {
  'vagrant-reload' => {
    'version' => '>= 0.0.1'
  }
}

Vagrant.configure('2') do |config|
  config.vagrant.plugins = required_plugins
  config.vm.box = 'AntonioMeireles/CLearLinux'
  config.vm.define 'gnome-desktop'
  config.vm.hostname = 'gnome.clearlinux.local'
  %w[vmware_fusion vmware_desktop vmware_workstation].each do |provider|
    config.vm.provider provider do |vmware|
      vmware.gui = true
      vmware.vmx[:memsize] = 8192
      vmware.vmx[:numvcpus] = 4
    end
  end
  config.vm.provision :bundle_add, bundles: ['desktop-autostart']
  config.vm.provision :reload
end
```

(the default password, for the `clearlinux` user is `V@grant!`)

Thanks in advance!

**Comment by ahkok** [comment]
Seems reasonable. I'm surprised we don't have this packaged yet, tbh.

**Comment by ahkok** [comment]
Done, will be in an update in 1-2 days.

**Comment by AntonioMeireles** [comment]
**THANKS**!

**Comment by AntonioMeireles** [comment]
@ahkok 

FWIW - things still not quite right ...

on `28380` i'm getting in `Xorg.1.log` 

``` 
(...)
[    46.780] (==) Assigned the driver to the xf86ConfigLayout
[    46.780] (II) LoadModule: "vmware"
[    46.780] (II) Loading /usr/lib64/xorg/modules/drivers/vmware_drv.so
[    46.780] (EE) Failed to load /usr/lib64/xorg/modules/drivers/vmware_drv.so: /usr/lib64/xorg/modules/drivers/vmware_drv.so: undefined symbol: vgaHWGetIndex
[    46.780] (EE) Failed to load module "vmware" (loader failed, 0)
(...)
```

Best Regards

**Comment by AntonioMeireles** [comment]
```
[   129.954] (II) Loading /usr/lib64/xorg/modules/drivers/vmware_drv.so
[   129.998] (II) Module vmware: vendor="X.Org Foundation"
[   129.998] 	compiled for 1.20.4, module version = 13.3.0
[   129.998] 	Module class: X.Org Video Driver
[   129.998] 	ABI class: X.Org Video Driver, version 24.0
```

*fixed* in *28430*! 

thanks @ahkok && @fenrus75 !
