### ISSUE TITLE
Gnome Online Accounts doesn't work as expected

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#599]
**Describe the bug**
In gnome settings, after I added online account (Google), nothing shows up in Calender or Evolution. 

**To Reproduce**
1. Add online accounts in gnome setting
2. Open Calender or Evolution and you'll see nothing shows up there

**Expected behavior**
As described in its [documentation](https://wiki.gnome.org/Projects/GnomeOnlineAccounts/Providers), one shall expects gnome Calender and Evolution to automatically shows calender events and emails from Google.

**Environment (please complete the following information):**
 - Clear Linux OS version: 
```
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=28630
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
```
 - Bundles: I will provide the list if needed.

**Additional context**
I only have data stored in Google, and please also check whether it works for other service providers.

P.S. #476 fixed a bug that adding online accounts always fails due to TLS error. This bug might be somewhat related.

**Comment by enx1998** [comment]
I have the same problem: after adding a google account nothing happen and no errors are shown neither in the UI nor in console.

**Comment by phmccarty** [comment]
Thanks for the feedback. I can reproduce as well have started investigation.

**Comment by mrkz** [comment]
Running `gnome-control-center` with --verbose option provides the following information:
```bash
$ gnome-control-center --verbose 
17:42:42.0942          network-cc-panel:    DEBUG: coldplugging devices
17:42:42.0942          network-cc-panel:    DEBUG: device /sys/devices/pci0000:00/0000:00:1c.6/0000:02:00.0/net/wlp2s0 type 2 path /org/freedesktop/NetworkManager/Devices/2
17:42:42.0942          network-cc-panel:    DEBUG: Calling handle_argv() after cold-plugging devices
(gnome-control-center:6909): dconf-DEBUG: 17:42:47.813: change_fast
(gnome-control-center:6909): dconf-DEBUG: 17:42:47.813: change_notify: /org/gnome/control-center/last-panel
17:42:47.0816                  GLib-GIO:    DEBUG: Failed to initialize portal (GNetworkMonitorPortal) for gio-network-monitor: Not using portals
17:42:47.0817                  GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation networkmanager (GNetworkMonitorNM) for ‘gio-network-monitor’
(gnome-control-center:6909): dconf-DEBUG: 17:42:47.819: watch_fast: "/org/gnome/online-accounts/" (establishing: 0, active: 0)
17:42:47.0819                GoaBackend:    DEBUG: Loading all providers: 
17:42:47.0819                GoaBackend:    DEBUG:  - google
17:42:47.0819                GoaBackend:    DEBUG:  - owncloud
17:42:47.0819                GoaBackend:    DEBUG:  - facebook
17:42:47.0819                GoaBackend:    DEBUG:  - windows_live
17:42:47.0819                GoaBackend:    DEBUG:  - flickr
17:42:47.0819                GoaBackend:    DEBUG:  - pocket
17:42:47.0819                GoaBackend:    DEBUG:  - foursquare
17:42:47.0819                GoaBackend:    DEBUG:  - exchange
17:42:47.0819                GoaBackend:    DEBUG:  - imap_smtp
17:42:47.0819                GoaBackend:    DEBUG:  - kerberos
(gnome-control-center:6909): dconf-DEBUG: 17:42:47.819: watch_established: "/org/gnome/online-accounts/" (establishing: 1)
17:42:47.0819                GoaBackend:    DEBUG: activated kerberos provider
(gnome-control-center:6909): dconf-DEBUG: 17:42:47.819: unwatch_fast: "/org/gnome/online-accounts/" (active: 1, establishing: 0)
17:42:47.0823                 cc-window:    DEBUG: Time to open panel 'Online Accounts': 0.009276s
17:42:47.0823                 cc-window:    DEBUG: Added 'network' to the previous panels
(gnome-control-center:6909): dconf-DEBUG: 17:42:47.824: unwatch_fast: "/system/proxy/http/" (active: 1, establishing: 0)
(gnome-control-center:6909): dconf-DEBUG: 17:42:47.824: unwatch_fast: "/system/proxy/ftp/" (active: 1, establishing: 0)
(gnome-control-center:6909): dconf-DEBUG: 17:42:47.824: unwatch_fast: "/system/proxy/" (active: 1, establishing: 0)
(gnome-control-center:6909): dconf-DEBUG: 17:42:47.824: unwatch_fast: "/system/proxy/https/" (active: 1, establishing: 0)
(gnome-control-center:6909): dconf-DEBUG: 17:42:47.825: unwatch_fast: "/system/proxy/socks/" (active: 1, establishing: 0)
(process:6922): GLib-GIO-DEBUG: 17:42:49.231: Failed to initialize portal (GNetworkMonitorPortal) for gio-network-monitor: Not using portals
(process:6922): GLib-GIO-DEBUG: 17:42:49.232: _g_io_module_get_default: Found default implementation networkmanager (GNetworkMonitorNM) for ?gio-network-monitor?
(process:6922): GLib-GIO-DEBUG: 17:42:49.234: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ?gio-vfs?
(WebKitWebProcess:6921): GLib-GIO-DEBUG: 17:42:49.244: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
(WebKitWebProcess:6921): GLib-GIO-DEBUG: 17:42:49.370: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(WebKitWebProcess:6921): dconf-DEBUG: 17:42:49.370: watch_fast: "/org/gnome/online-accounts/" (establishing: 0, active: 0)
(WebKitWebProcess:6921): GoaBackend-DEBUG: 17:42:49.370: Loading all providers: 
(WebKitWebProcess:6921): GoaBackend-DEBUG: 17:42:49.370:  - google
(WebKitWebProcess:6921): GoaBackend-DEBUG: 17:42:49.370:  - owncloud
(WebKitWebProcess:6921): GoaBackend-DEBUG: 17:42:49.370:  - facebook
(WebKitWebProcess:6921): GoaBackend-DEBUG: 17:42:49.370:  - windows_live
(WebKitWebProcess:6921): GoaBackend-DEBUG: 17:42:49.370:  - flickr
(WebKitWebProcess:6921): GoaBackend-DEBUG: 17:42:49.370:  - pocket
(WebKitWebProcess:6921): GoaBackend-DEBUG: 17:42:49.370:  - foursquare
(WebKitWebProcess:6921): GoaBackend-DEBUG: 17:42:49.370:  - exchange
(WebKitWebProcess:6921): GoaBackend-DEBUG: 17:42:49.370:  - imap_smtp
(WebKitWebProcess:6921): GoaBackend-DEBUG: 17:42:49.370:  - kerberos
(WebKitWebProcess:6921): GoaBackend-DEBUG: 17:42:49.370: activated kerberos provider
(WebKitWebProcess:6921): dconf-DEBUG: 17:42:49.370: unwatch_fast: "/org/gnome/online-accounts/" (active: 0, establishing: 1)
(WebKitWebProcess:6921): dconf-DEBUG: 17:42:49.370: watch_established: "/org/gnome/online-accounts/" (establishing: 0)
(process:6922): GLib-GIO-DEBUG: 17:42:49.384: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ?gsettings-backend?
(process:6922): dconf-DEBUG: 17:42:49.384: watch_fast: "/system/proxy/" (establishing: 0, active: 0)
(process:6922): dconf-DEBUG: 17:42:49.384: watch_fast: "/system/proxy/http/" (establishing: 0, active: 0)
(process:6922): dconf-DEBUG: 17:42:49.384: watch_fast: "/system/proxy/https/" (establishing: 0, active: 0)
(process:6922): dconf-DEBUG: 17:42:49.384: watch_fast: "/system/proxy/ftp/" (establishing: 0, active: 0)
(process:6922): dconf-DEBUG: 17:42:49.384: watch_fast: "/system/proxy/socks/" (establishing: 0, active: 0)
(process:6922): GLib-GIO-DEBUG: 17:42:49.384: _g_io_module_get_default: Found default implementation gnome (GProxyResolverGnome) for ?gio-proxy-resolver?
(process:6922): dconf-DEBUG: 17:42:49.384: watch_established: "/system/proxy/" (establishing: 1)
(process:6922): dconf-DEBUG: 17:42:49.384: watch_established: "/system/proxy/http/" (establishing: 1)
(process:6922): dconf-DEBUG: 17:42:49.384: watch_established: "/system/proxy/https/" (establishing: 1)
(process:6922): dconf-DEBUG: 17:42:49.384: watch_established: "/system/proxy/ftp/" (establishing: 1)
(process:6922): dconf-DEBUG: 17:42:49.384: watch_established: "/system/proxy/socks/" (establishing: 1)
(process:6922): GLib-GIO-DEBUG: 17:42:49.388: _g_io_module_get_default: Found default implementation gnutls (GTlsBackendGnutls) for ?gio-tls-backend?
(WebKitWebProcess:6921): GLib-GIO-DEBUG: 17:42:49.696: _g_io_module_get_default: Found default implementation gnutls (GTlsBackendGnutls) for ‘gio-tls-backend’
17:42:49.0697                  GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation gnutls (GTlsBackendGnutls) for ‘gio-tls-backend’




(gnome-control-center:6909): dconf-DEBUG: 17:43:30.052: watch_fast: "/system/proxy/" (establishing: 0, active: 0)
(gnome-control-center:6909): dconf-DEBUG: 17:43:30.052: watch_fast: "/system/proxy/http/" (establishing: 0, active: 0)
(gnome-control-center:6909): dconf-DEBUG: 17:43:30.052: watch_fast: "/system/proxy/https/" (establishing: 0, active: 0)
(gnome-control-center:6909): dconf-DEBUG: 17:43:30.052: watch_fast: "/system/proxy/ftp/" (establishing: 0, active: 0)
(gnome-control-center:6909): dconf-DEBUG: 17:43:30.052: watch_fast: "/system/proxy/socks/" (establishing: 0, active: 0)
17:43:30.0052                  GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation gnome (GProxyResolverGnome) for ‘gio-proxy-resolver’
(gnome-control-center:6909): dconf-DEBUG: 17:43:30.052: watch_established: "/system/proxy/" (establishing: 1)
(gnome-control-center:6909): dconf-DEBUG: 17:43:30.052: watch_established: "/system/proxy/http/" (establishing: 1)
(gnome-control-center:6909): dconf-DEBUG: 17:43:30.052: watch_established: "/system/proxy/https/" (establishing: 1)
(gnome-control-center:6909): dconf-DEBUG: 17:43:30.052: watch_established: "/system/proxy/ftp/" (establishing: 1)
(gnome-control-center:6909): dconf-DEBUG: 17:43:30.052: watch_established: "/system/proxy/socks/" (establishing: 1)
(gnome-control-center:6909): GoaBackend-DEBUG: 17:43:30.175: < HTTP/1.1 6 Unacceptable TLS certificate
(gnome-control-center:6909): GoaBackend-DEBUG: 17:43:30.175: < Soup-Debug-Timestamp: 1556577810
(gnome-control-center:6909): GoaBackend-DEBUG: 17:43:30.175: < Soup-Debug: SoupMessage 0 (0x1dc3680)
(gnome-control-center:6909): GoaBackend-DEBUG: 17:43:30.175:   
(process:7005): GLib-GIO-DEBUG: 17:43:36.294: Failed to initialize portal (GNetworkMonitorPortal) for gio-network-monitor: Not using portals
(process:7005): GLib-GIO-DEBUG: 17:43:36.297: _g_io_module_get_default: Found default implementation networkmanager (GNetworkMonitorNM) for ?gio-network-monitor?
(process:7005): GLib-GIO-DEBUG: 17:43:36.300: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ?gio-vfs?
(WebKitWebProcess:7004): GLib-GIO-DEBUG: 17:43:36.300: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
(WebKitWebProcess:7004): GLib-GIO-DEBUG: 17:43:36.411: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(WebKitWebProcess:7004): dconf-DEBUG: 17:43:36.411: watch_fast: "/org/gnome/online-accounts/" (establishing: 0, active: 0)
(WebKitWebProcess:7004): GoaBackend-DEBUG: 17:43:36.411: Loading all providers: 
(WebKitWebProcess:7004): GoaBackend-DEBUG: 17:43:36.411:  - google
(WebKitWebProcess:7004): GoaBackend-DEBUG: 17:43:36.411:  - owncloud
(WebKitWebProcess:7004): GoaBackend-DEBUG: 17:43:36.411:  - facebook
(WebKitWebProcess:7004): GoaBackend-DEBUG: 17:43:36.411:  - windows_live
(WebKitWebProcess:7004): GoaBackend-DEBUG: 17:43:36.411:  - flickr
(WebKitWebProcess:7004): GoaBackend-DEBUG: 17:43:36.411:  - pocket
(WebKitWebProcess:7004): GoaBackend-DEBUG: 17:43:36.411:  - foursquare
(WebKitWebProcess:7004): GoaBackend-DEBUG: 17:43:36.412:  - exchange
(WebKitWebProcess:7004): GoaBackend-DEBUG: 17:43:36.412:  - imap_smtp
(WebKitWebProcess:7004): GoaBackend-DEBUG: 17:43:36.412:  - kerberos
(WebKitWebProcess:7004): dconf-DEBUG: 17:43:36.412: watch_established: "/org/gnome/online-accounts/" (establishing: 1)
(WebKitWebProcess:7004): GoaBackend-DEBUG: 17:43:36.412: activated kerberos provider
(WebKitWebProcess:7004): dconf-DEBUG: 17:43:36.412: unwatch_fast: "/org/gnome/online-accounts/" (active: 1, establishing: 0)
(process:7005): GLib-GIO-DEBUG: 17:43:36.424: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ?gsettings-backend?
(process:7005): dconf-DEBUG: 17:43:36.424: watch_fast: "/system/proxy/" (establishing: 0, active: 0)
(process:7005): dconf-DEBUG: 17:43:36.424: watch_fast: "/system/proxy/http/" (establishing: 0, active: 0)
(process:7005): dconf-DEBUG: 17:43:36.424: watch_fast: "/system/proxy/https/" (establishing: 0, active: 0)
(process:7005): dconf-DEBUG: 17:43:36.424: watch_fast: "/system/proxy/ftp/" (establishing: 0, active: 0)
(process:7005): dconf-DEBUG: 17:43:36.424: watch_fast: "/system/proxy/socks/" (establishing: 0, active: 0)
(process:7005): GLib-GIO-DEBUG: 17:43:36.424: _g_io_module_get_default: Found default implementation gnome (GProxyResolverGnome) for ?gio-proxy-resolver?
(process:7005): dconf-DEBUG: 17:43:36.424: watch_established: "/system/proxy/" (establishing: 1)
(process:7005): dconf-DEBUG: 17:43:36.424: watch_established: "/system/proxy/http/" (establishing: 1)
(process:7005): dconf-DEBUG: 17:43:36.424: watch_established: "/system/proxy/https/" (establishing: 1)
(process:7005): dconf-DEBUG: 17:43:36.424: watch_established: "/system/proxy/ftp/" (establishing: 1)
(process:7005): dconf-DEBUG: 17:43:36.424: watch_established: "/system/proxy/socks/" (establishing: 1)
(process:7005): GLib-GIO-DEBUG: 17:43:36.432: _g_io_module_get_default: Found default implementation gnutls (GTlsBackendGnutls) for ?gio-tls-backend?
(WebKitWebProcess:7004): GLib-GIO-DEBUG: 17:43:36.994: _g_io_module_get_default: Found default implementation gnutls (GTlsBackendGnutls) for ‘gio-tls-backend’


(gnome-control-center:6909): GoaBackend-DEBUG: 17:44:03.024: < HTTP/1.1 6 Unacceptable TLS certificate
(gnome-control-center:6909): GoaBackend-DEBUG: 17:44:03.024: < Soup-Debug-Timestamp: 1556577843
(gnome-control-center:6909): GoaBackend-DEBUG: 17:44:03.024: < Soup-Debug: SoupMessage 0 (0x2f628c0)
(gnome-control-center:6909): GoaBackend-DEBUG: 17:44:03.024:   



(WebKitWebProcess:7061): GLib-GIO-DEBUG: 17:44:09.004: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
(process:7063): GLib-GIO-DEBUG: 17:44:09.011: Failed to initialize portal (GNetworkMonitorPortal) for gio-network-monitor: Not using portals
(process:7063): GLib-GIO-DEBUG: 17:44:09.013: _g_io_module_get_default: Found default implementation networkmanager (GNetworkMonitorNM) for ?gio-network-monitor?
(process:7063): GLib-GIO-DEBUG: 17:44:09.015: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ?gio-vfs?
(WebKitWebProcess:7061): GLib-GIO-DEBUG: 17:44:09.141: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(WebKitWebProcess:7061): dconf-DEBUG: 17:44:09.141: watch_fast: "/org/gnome/online-accounts/" (establishing: 0, active: 0)
(WebKitWebProcess:7061): GoaBackend-DEBUG: 17:44:09.141: Loading all providers: 
(WebKitWebProcess:7061): GoaBackend-DEBUG: 17:44:09.141:  - google
(WebKitWebProcess:7061): GoaBackend-DEBUG: 17:44:09.141:  - owncloud
(WebKitWebProcess:7061): GoaBackend-DEBUG: 17:44:09.141:  - facebook
(WebKitWebProcess:7061): GoaBackend-DEBUG: 17:44:09.141:  - windows_live
(WebKitWebProcess:7061): GoaBackend-DEBUG: 17:44:09.141:  - flickr
(WebKitWebProcess:7061): GoaBackend-DEBUG: 17:44:09.141:  - pocket
(WebKitWebProcess:7061): GoaBackend-DEBUG: 17:44:09.141:  - foursquare
(WebKitWebProcess:7061): GoaBackend-DEBUG: 17:44:09.141:  - exchange
(WebKitWebProcess:7061): GoaBackend-DEBUG: 17:44:09.141:  - imap_smtp
(WebKitWebProcess:7061): GoaBackend-DEBUG: 17:44:09.141:  - kerberos
(WebKitWebProcess:7061): GoaBackend-DEBUG: 17:44:09.141: activated kerberos provider
(WebKitWebProcess:7061): dconf-DEBUG: 17:44:09.141: unwatch_fast: "/org/gnome/online-accounts/" (active: 0, establishing: 1)
(WebKitWebProcess:7061): dconf-DEBUG: 17:44:09.142: watch_established: "/org/gnome/online-accounts/" (establishing: 0)
(process:7063): GLib-GIO-DEBUG: 17:44:09.159: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ?gsettings-backend?
(process:7063): dconf-DEBUG: 17:44:09.159: watch_fast: "/system/proxy/" (establishing: 0, active: 0)
(process:7063): dconf-DEBUG: 17:44:09.159: watch_fast: "/system/proxy/http/" (establishing: 0, active: 0)
(process:7063): dconf-DEBUG: 17:44:09.159: watch_fast: "/system/proxy/https/" (establishing: 0, active: 0)
(process:7063): dconf-DEBUG: 17:44:09.159: watch_fast: "/system/proxy/ftp/" (establishing: 0, active: 0)
(process:7063): dconf-DEBUG: 17:44:09.159: watch_fast: "/system/proxy/socks/" (establishing: 0, active: 0)
(process:7063): GLib-GIO-DEBUG: 17:44:09.159: _g_io_module_get_default: Found default implementation gnome (GProxyResolverGnome) for ?gio-proxy-resolver?
(process:7063): dconf-DEBUG: 17:44:09.159: watch_established: "/system/proxy/" (establishing: 1)
(process:7063): dconf-DEBUG: 17:44:09.160: watch_established: "/system/proxy/http/" (establishing: 1)
(process:7063): dconf-DEBUG: 17:44:09.160: watch_established: "/system/proxy/https/" (establishing: 1)
(process:7063): dconf-DEBUG: 17:44:09.160: watch_established: "/system/proxy/ftp/" (establishing: 1)
(process:7063): dconf-DEBUG: 17:44:09.160: watch_established: "/system/proxy/socks/" (establishing: 1)
(process:7063): GLib-GIO-DEBUG: 17:44:09.166: _g_io_module_get_default: Found default implementation gnutls (GTlsBackendGnutls) for ?gio-tls-backend?
(WebKitWebProcess:7061): GLib-GIO-DEBUG: 17:44:09.611: _g_io_module_get_default: Found default implementation gnutls (GTlsBackendGnutls) for ‘gio-tls-backend’
(gnome-control-center:6909): GoaBackend-DEBUG: 17:44:30.759: < HTTP/1.1 6 Unacceptable TLS certificate
(gnome-control-center:6909): GoaBackend-DEBUG: 17:44:30.759: < Soup-Debug-Timestamp: 1556577870
(gnome-control-center:6909): GoaBackend-DEBUG: 17:44:30.759: < Soup-Debug: SoupMessage 0 (0x2f62aa0)
(gnome-control-center:6909): GoaBackend-DEBUG: 17:44:30.759:   



(gnome-control-center:6909): dconf-DEBUG: 17:44:38.542: unwatch_fast: "/org/gnome/control-center/" (active: 1, establishing: 0)
(gnome-control-center:6909): dconf-DEBUG: 17:44:38.542: sync
17:44:38.0542         cc-object-storage:    DEBUG: Destroying cached objects
```

This is from several attempts to connect to different accounts. (Google/Microsoft/Facebook)

Also, similar issue reported on https://github.com/Dlackware/gnome/issues/12 , @phmccarty  maybe worth to check is we're down the same issue.

**Comment by phmccarty** [comment]
@mrkz Thanks for the help! I had not tried using the `--verbose` option yet, but it appears to be providing very helpful hints.

**Comment by isalgueiro** [comment]
I'm getting the same TLS error here on a fresh install. Tried the Dlackware/gnome#12 workaround adapted to what I see in my clear linux install, but gnome-control-center is still failing.

This is what I tried:

```
for i in `ls /usr/share/ca-certs/trusted/*.crt`; do cat $i >> /etc/ssl/ca-bundle.crt; done;
```

Please let me know if I can test something else.

**Comment by phmccarty** [comment]
I have not had a chance to track down the root cause here yet. At first, I thought there might be an untrusted cert in the cert chain for the request, but after adding that cert as a trusted anchor, the issue recurred.

@mrkz Can you continue the investigation? I will unassign myself.

**Comment by harpingon** [comment]
I still see this as a problem in 30940

Was hoping to use the feature as a replacement for "insync" to access Google Drive files, because InSync isn't supported on Clear.

**Comment by xopher-mc** [comment]
Upgrade to 3.34 hasn't fixed this issue.

**Comment by mrkz** [comment]
Hey, this is still on my radar and currently working on it.

As far as I've noticed, it seems that the regression may be because of the removal of the backend we rely on for HTTPS handling (pkcs#11) on glib-networking.

I'll continue to update the issue as I progress on the root-causing/fixes :)

**Comment by harpingon** [comment]
Looks like pkcs#11 just got added to glib-networking in a 6000-odd line commit

https://gitlab.gnome.org/GNOME/glib-networking/commit/be1d64042226b73653be6aad033cf88c3b96aa58

**Comment by gmagic** [comment]
Can confirm this issue!

i can't add Google Account (corporate gsuite) in Gnome.
I've passed all steps of Google authentication but after last step there's no any google account in gnome cloud accounts. I've done it several times.

By the way IMAP / SMTP account have been added successfully.

Clear Linux OS (31270)

**Comment by Unixware** [comment]
seriously, this issue is still open since April

**Comment by SkavenNoises** [comment]
Clean install of Manjaro-Gnome has given me this problem too. Would love to see it fixed

**Comment by vinyanalista** [comment]
I'm not sure this information can help Clear Linux, but with [Linux Kamarada](https://kamarada.github.io/) ([openSUSE](https://www.opensuse.org/)-based), I solved this issue updating the [`glib-networking`](https://software.opensuse.org/package/glib-networking) package.

**Comment by carolosf** [comment]
I have this issue too on a clean install on two laptops.

**Comment by chickenlol** [comment]
Still experiencing this issue on a clean install.  I rely on deja-dup for my laptop backups and I need this feature to utilize it fully...

**Comment by someone2048** [comment]
I as well have the issue

**Comment by AlessandroFasse** [comment]
Any solution on this?

**Comment by SkavenNoises** [comment]
I can't give a ticket resolution or anything like that. But after a few big
updates on stable it seemed to get resolved

**Comment by daveg208** [comment]
I have just done a clean install  and have exactly the same issues as above.

I take it that this is not a priority for anyone ?
I know the devs are busy, but 10 months is quite a while for a bug of this nature.

Cheers

Dave

**Comment by 2pk03** [comment]
/bump
@SkavenNoises - when will that happen?

**Comment by brocgailit** [comment]
Hi @mrkz I noticed this has been marked as **In Progress** since Jul 30.  Are there any updates since your last comment in October https://github.com/clearlinux/distribution/issues/599#issuecomment-539213443?

**Comment by slrtbtfs** [comment]
As a work around for this issue, it is possible to use the flatpak version of evolution, which works fine (at least for me).

**Comment by 2pk03** [comment]
@slrtbtfs Unfortunately this workaround does not work with enterprise GSuite accounts as it should, collection discovery works fine with @gmail accounts. Enabling IMAP for GSuite is not the best solution in my opinion. Additionally the integrated contacts and calendar will not work since they are hooked into the OnlineAccounts. 
@mrkz - Status? Quite now CL is a great distro, but _not_ fixing this bug since almost 9 month is not a solution...

**Comment by AlessandroFasse** [comment]
Is there any update on this? I would really appreciate if I could use my google account on clearlinux.

**Comment by bryteise** [comment]
Just dipping my toe into this as I am not going to be spending time debugging. It looks like all the dependencies are up to date and using ```gnutls-cli -d 5 google.com -p 443``` reports using tls v1.3 and the handshake completing. Maybe somewhere in the gnome stack.

**Comment by ordogresso** [comment]
Hi there! 
I would love to see this feature working. Is it possible to help you guys anyhow? (Debugging/testing whatever)?

Thanks.

**Comment by rossburton** [comment]
Good news! I can replicate and so can glib-networking upstream. The good question is why a minimal test case fails but Epiphany works...

**Comment by rossburton** [comment]
So the basic problem is that librest is trying to verify certificates, and failing.

**Comment by rossburton** [comment]
Patch sent.  We were telling rest to look in the wrong place for certificates.

**Comment by rossburton** [comment]
Fixed in librest 0.8.1-11, just merged.

**Comment by lebensterben** [comment]
@rossburton thanks for the patch and I no longer see same error message from `gnome-control-center --verbose`. But there're some thing still not quite working as expected.

1. Even after I added my Gmail account, nothing shows up in `gnome-calender`

2. For `geary`, I first started `gnome-control-center --verbose`, then I launched `geary` and it asks me to add an account. I clicked `Gmail` account and it brings me to the `Online Accounts` tab of `gnome-calender`. After adding the Gmail account, somehow `geary` still requires me to input my email address and password. (I don't know whether this is expected behaviour, but why bother login twice?)
  The output from `gnome-control-center` and a screenshot is attached below.
![Screenshot from 2020-03-04 14-49-41](https://user-images.githubusercontent.com/1222865/75917678-5a9a8400-5e28-11ea-969d-5395f93151e0.png)

[gnome-control-center-output.txt](https://github.com/clearlinux/distribution/files/4289426/gnome-control-center-output.txt)

**Comment by rossburton** [comment]
The fix hasn't actually rolled out into a release yet.  I'll update this bug when it has.

**Comment by GonerGenesis** [comment]
A Workaround for the time being is to use Thunderbird-->Lightning-->Provider for Google Calendar

**Comment by lebensterben** [comment]
> The fix hasn't actually rolled out into a release yet. I'll update this bug when it has.

I can confirm that it's working. Thanks.

**Comment by nazar2sfive** [comment]
@lebensterben @rossburton 
![image](https://user-images.githubusercontent.com/12841320/80862091-23aee600-8c92-11ea-92e5-811d77ce5ee5.png)

**Comment by 0cool-f** [comment]
labeled "closed" but is not closed at all, I had this bug today, google and other socials don't show anything when clicking on them, the only way to fix it was this command `sudo glib-compile-schemas /usr/share/glib-2.0/schemas/`
