### ISSUE TITLE
Clearlinux docker image: pkg-config fails

### ISSUE THREAD

**Issue by mcastelino** [clearlinux/distribution#831]
# Clearlinux docker image: pkg-config fails

pkg-config fails with error
```
pkg-config: error while loading shared libraries: libglib-2.0.so.0: cannot open shared object file: No such file or directory
```

If the Dockerfile used to build is

```
FROM clearlinux:base AS build
RUN swupd update && swupd bundle-add c-basic-legacy
RUN pkg-config
```

But will work if the Dockerfile is

```
FROM clearlinux:base AS build

RUN swupd update
RUN swupd bundle-add c-basic-legacy
RUN pkg-config
```

**Comment by mcastelino** [comment]
Even more interesting

```
FROM clearlinux:base AS build
RUN swupd update && swupd bundle-add c-basic-legacy && pkg-config --version
RUN pkg-config
```

It breaks between layers. At the first layer pkg-config works. At the next layer somehow we have lost the cache.

**Comment by mdhorn** [comment]
@mcastelino Out of curiosity, what platform are you running Docker under? Something other than Clear Linux* OS?

**Comment by mcastelino** [comment]
@mdhorn 

Environment

```
docker info
Server Version: 18.06.2-ce
Storage Driver: devicemapper
 Backing Filesystem: xfs
 Udev Sync Supported: true
Kernel Version: 5.0.11-050011-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by mcastelino** [comment]
Some more debug details. The softlink seems to be changing locations

Dockerfile
```
FROM clearlinux:base AS build
RUN swupd update && swupd bundle-add c-basic-legacy && pkg-config --version && ls -l /usr/lib64/libgio-2.0.so.0 && ls -H /usr/lib64/libgio-2.0.so.0
RUN ls -l /usr/lib64/libgio-2.0.so.0
RUN ls -H /usr/lib64/libgio-2.0.so.0
RUN pkg-config --version
```

```
Calling post-update helper scripts.
Successfully installed 2 bundles
0.29.2
lrwxrwxrwx 1 root root 22 Feb  1 20:26 /usr/lib64/libgio-2.0.so.0 -> libgio-2.0.so.0.6000.3
/usr/lib64/libgio-2.0.so.0
Removing intermediate container 8951bcf6e19a
 ---> b6e44736ca76
Step 3/5 : RUN ls -l /usr/lib64/libgio-2.0.so.0
 ---> Running in 53ced2b3d514
lrwxrwxrwx 1 root root 22 Feb  1 20:26 /usr/lib64/libgio-2.0.so.0 -> libgio-2.0.so.0.6000.2
Removing intermediate container 53ced2b3d514
 ---> bae64fad3107
Step 4/5 : RUN ls -H /usr/lib64/libgio-2.0.so.0
 ---> Running in f42a2dc92d0a
ls: cannot access '/usr/lib64/libgio-2.0.so.0': No such file or directory
The command '/bin/sh -c ls -H /usr/lib64/libgio-2.0.so.0' returned a non-zero code: 2
```

**Comment by chivakker** [comment]
I was also seeing this problem, running ldconfig as a workaround works just fine, I have seen it with a number of libraries and ldconfig will fix.

**Comment by mcastelino** [comment]
@bryteise , some good news. This seems to be a docker bug which has been fixed in the latest releases. Now with latest version of docker (and overlay2) this issue goes away. (I do not think this is a devicemapper vs overlay2 issue, but it could be that too).

```
Server Version: 18.09.6
```

As we hold the docker version to `18.06.2-ce` as we need Devicemapper for firecracker as well as optimal performance with kata, we see this issue in Clearlinux.

/cc @chivakker @mdhorn

**Comment by bryteise** [comment]
I think we've fixed this at the kernel level at this point, re-open if that's not the case.

**Comment by gvancuts** [comment]
I'm seeing this issue still today, based on the analysis above, is it expected given that the Docker version shipped with Clear Linux still is at `18.06.3`? If correct, I would suggest to keep this issue open until this is expected to work out of the box in Clear Linux.

**Comment by bryteise** [comment]
@gvancuts Is the host system running a Clear Linux kernel? Which kernel is it using?

**Comment by gvancuts** [comment]
Yes, this is the kernel I am currently running: `org.clearlinux.native.5.2.8-818`

**Comment by mythi** [comment]
@gvancuts I think the overlay patch was added later than that. You'd need something like 5.2.9-826

**Comment by gvancuts** [comment]
Thanks @mythi , let me try to upgrade my system and I'll get back to you!

**Comment by gvancuts** [comment]
> Thanks @mythi , let me try to upgrade my system and I'll get back to you!

Upgraded my system and now running kernel `5.3.1-843.native`, I'm no longer seeing the issue. Thanks!!
