### ISSUE TITLE
Video thumbnails in gnome/nautilus

### ISSUE THREAD

**Issue by ahkok** [clearlinux/distribution#885]

**Comment by puneetse** [comment]
For reference: https://github.com/clearlinux/distribution/issues/701
This sounds like a related issue.

**Comment by mrkz** [comment]
This should be fixed along with https://github.com/clearlinux/distribution/issues/701#issuecomment-503205313 fix.


For *.mp4 files no thumbnail is generated due to the following:
```
** Message: 14:15:59.946: Missing plugin: gstreamer|1.0|totem|MPEG-4 AAC decoder|decoder-audio/mpeg, mpegversion=(int)4, level=(string)2, base-profile=(string)lc, profile=(string)lc (MPEG-4 AAC decoder)
```

But I tested for webm files successfully.

**Comment by mrkz** [comment]
Release **29980** is available now :+1: 

In order to re-create the failed thumbnails, please run the following in a terminal:
```bash
$ rm -rf ~/.cache/thumbnails/fail/gnome-thumbnail-factory/*
```

New installs or new users should not need to run the previous command as those may be unaffected from 29980 and afterward.

Please notice that `*.mp4` files thumbnail is still failing as previous comment states.

Thanks for the bug report! :tada:

**Comment by AnwarShah** [comment]
@mrkz `*.mp4` files thumbnails are still failing. Should I create a new issue or this can be re-opened?

**Comment by thiagomacieira** [comment]
Please don't. We are unable to provide support for .mp4 files in Clear. They will fail and this is expected.

**Comment by uohmak4fvpqe** [comment]
How can we get it manually then ? Instructions on that would be appreciated in the documentation
