### ISSUE TITLE
Error and warning messages during R startup

### ISSUE THREAD

**Issue by rahulunair** [clearlinux/distribution#991]
Tried installing R-basic on a container, ClearLinux version: 30140
```
~ $ docker run -it clearlinux  
```
I am getting the below error:

```bash
Unable to find image 'clearlinux:latest' locally
latest: Pulling from library/clearlinux
af5b3c940b35: Pull complete 
Digest: sha256:52380a12ddc58324ca20cc17daa21cde1dc74fdddfc91f2f34d6bd18bb98ade2
Status: Downloaded newer image for clearlinux:latest
root@d65f0096ebd5/ # swupd bundle-add R-basic
Loading required manifests...
Downloading packs (417.98 Mb) for:
 - R-basic
 - libX11client
 - lib-opengl
 - devpkg-R
 - devpkg-base
 - c-basic
 - perl-basic
 - lib-openssl
 - nasm
 - binutils
 - bison
 - flex
 - glibc-locale
 - llvm
 - make
 - less
	...100%
Finishing packs extraction...
No extra files need to be downloaded
Installing bundle(s) files...
	...100%
Calling post-update helper scripts.
Successfully installed 1 bundle
root@d65f0096ebd5/ # R

R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-generic-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Error: package or namespace load failed for ‘utils’:
 .onLoad failed in loadNamespace() for 'utils', details:
  call: system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE)
  error: error in running command
Error: package or namespace load failed for ‘stats’:
 .onLoad failed in loadNamespace() for 'utils', details:
  call: system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE)
  error: error in running command
During startup - Warning messages:
1: package ‘utils’ in options("defaultPackages") was not found 
2: package ‘stats’ in options("defaultPackages") was not found
```

Is this expected?

**Comment by phmccarty** [comment]
@rahulunair Can you retest this issue as well on a newer Clear release?

**Comment by phmccarty** [comment]
This was indeed a bug in the `R` package; it was missing a runtime dependency on `which`. I added that dependency, so this should be fixed early next week.

**Comment by UkkoCB** [comment]
Hi, 

Could it be that this issue still exists in R-3.4.1-1.52.amzn1.x86_64?

Thanks!

**Comment by fenrus75** [comment]
that does not look like something that came from us ?

**Comment by phmccarty** [comment]
@UkkoCB The rpms for Clear Linux OS are named differently. In this instance, the rpm with the fix had the name `R-3.6.1-125.x86_64`.

**Comment by UkkoCB** [comment]
Oh, I see. Sorry for the misunderstanding and thanks for the quick reply
